class_name GameEnums
extends RefCounted

enum Rank { PAWN, KNIGHT, ROOK, BISHOP, QUEEN, KING }
enum Faction { PLAYER, ENEMY, OUTSIDER }
enum BuildingType { FARM, MATERIAL_WORKSHOP, PRISON, INFIRMARY, BARRACKS }
enum BuildingPhase { BLUEPRINT, BUILDING, ACTIVE, DEMOLISHING }
enum JobRole {
	NONE, BUILDER, MANAGER, FARM_WORKER, WORKSHOP_MANAGER,
	TREATMENT, PRISON_MANAGER, PRISON_GUARD
}
enum FactConfidence { CONFIRMED, REPORTED, UNCERTAIN }
enum PrisonerAction { RELEASE, KILL, CONTINUE, SUBMIT }
enum ExpeditionStatus { AWAY, RETURN_PENDING, COMPLETE }
enum OutsiderAction { START_SUPPORT, STOP_SUPPORT, ACCEPT_TRADE, REJECT_TRADE, RESETTLE }
enum OutsidePressure { CALM, UNEASY, TENSE, RIOT }
enum Season { SPRING, SUMMER, AUTUMN, WINTER }
enum Weather { CLEAR, RAIN, STORM, COLD, HEAT }
enum RegionPresence { UNKNOWN, OBSERVED, VISITED, SUPPLIED, CONNECTED, INFLUENCED }
enum ResourcePressure { SURPLUS, STABLE, STRAINED, CRITICAL }
enum EventStatus { ACTIVE, WAITING_CHOICE, RESOLVED, CANCELLED }
enum AttentionLevel { NORMAL, NOTICE, IMPORTANT, CRITICAL }
enum InformationFreshness { FRESH, AGING, STALE }
enum RebellionLevel {
	NONE = -1, DISSATISFIED = 0, LOW_OUTPUT = 1, OBJECTS_BUT_OBEYS = 2, RESISTS = 3, REVOLT = 4
}
enum CityState { LOW, MEDIUM, HIGH }
