class_name Localization
extends RefCounted

const DEFAULT_LOCALE := "vi"
const FALLBACK_LOCALE := "en"
const SUPPORTED_LOCALES: Array[String] = ["vi", "en"]
const DEFAULT_STORAGE_PATH := "user://after_checkmate.cfg"

const VI := {
	"brand.name": "After Checkmate",
	"menu.subtitle": "TÀN CUỘC",
	"menu.play": "Chơi",
	"menu.about": "Giới Thiệu Game",
	"menu.settings": "Cài đặt",
	"menu.quit": "Thoát",
	"menu.about_title": "AFTER CHECKMATE · TÀN CUỘC",
	"menu.about_body": "Dẫn dắt một thành phố cờ vua đang đứng dậy sau chiến tranh. Quản lý lương thực, vật tư, những quân cờ còn sống và các quyết định vượt khỏi cổng thành. Đây là một thế giới đang hồi sinh, nơi mỗi lựa chọn để lại dấu vết.",
	"settings.title": "CÀI ĐẶT",
	"settings.resolution": "Độ phân giải",
	"settings.master": "Âm lượng tổng",
	"settings.bgm": "Nhạc nền",
	"settings.sfx": "Hiệu ứng",
	"settings.ambience": "Môi trường",
	"settings.mute": "Tắt toàn bộ âm thanh",
	"pause.title": "TẠM DỪNG",
	"pause.resume": "Tiếp tục",
	"pause.main_menu": "Thoát về màn hình chính",
	"common.close": "Đóng",
	"common.confirm": "Xác nhận",
	"common.cancel": "Hủy",
	"common.none": "Không có",
	"common.unknown": "Chưa rõ",
	"common.day": "Ngày {day}",
	"game.day_counter": "NGÀY {day} / {max_day}",
	"game.food": "Lương thực",
	"game.materials": "Vật tư",
	"game.resources": "   Lương thực {food}   ·   Vật tư {materials}",
	"game.season_weather": "   Mùa {season} · {weather}",
	"game.undo": "Đóng / Bỏ chọn",
	"game.undo_hint": "Đóng bảng hoặc bỏ thao tác tạm thời; không hủy lệnh đã định",
	"game.report": "Báo cáo",
	"game.world": "Thế giới",
	"game.end_day": "Kết thúc ngày",
	"game.resolved_day": "Đã giải quyết ngày {day}",
	"game.failure": "THẤT BẠI: {reason}",
	"failure.outsider_overrun": "{group} đã tràn vào thành trong hỗn loạn.",
	"game.starved": "Chết đói: {names}",
	"game.resource_delta": "{resource} {delta}",
	"rank.pawn": "Tốt",
	"rank.knight": "Mã",
	"rank.rook": "Xe",
	"rank.bishop": "Tịnh",
	"rank.queen": "Hậu",
	"rank.king": "Vua",
	"faction.player": "Phe ta",
	"faction.enemy": "Địch",
	"faction.outsider": "Bên ngoài",
	"building.farm": "Nông trại",
	"building.workshop": "Xưởng vật tư",
	"building.prison": "Nhà giam",
	"building.infirmary": "Y xá",
	"building.barracks": "Doanh trại",
	"building.phase.blueprint": "Dự kiến",
	"building.phase.building": "Đang xây",
	"building.phase.active": "Hoạt động",
	"building.phase.demolishing": "Đang phá",
	"building.palette.title": "CÔNG TRÌNH 3×3",
	"building.palette.hint": "Ô lõi ở giữa, 8 ô vận hành xung quanh",
	"building.palette.builders": "THỢ XÂY",
	"building.palette.builder_count": "Đã chọn {count} thợ xây",
	"building.palette.cancel_plan": "Hủy công trình dự kiến",
	"building.palette.cancel_current": "Hủy xây hiện tại",
	"building.palette.assign_builder": "Gán thợ xây đã chọn",
	"building.palette.demolish": "Phá công trình đang hoạt động",
	"building.palette.cancel_demolition": "Hủy lệnh phá",
	"building.palette.staffing": "PHÂN CÔNG",
	"building.palette.assign_manager": "Gán quân đã chọn làm quản lý",
	"building.palette.assign_worker": "Gán quân đã chọn làm lao động",
	"building.palette.cancel_staffing": "Hủy phân công dự kiến",
	"building.palette.choose": "Chọn một loại công trình",
	"building.palette.builder_role": "thợ xây",
	"report.title": "BÁO CÁO NGÀY",
	"report.day_title": "BÁO CÁO NGÀY {day}",
	"report.attention": "CẦN CHÚ Ý",
	"report.today_summary": "TÓM TẮT HÔM NAY",
	"report.full_log": "TOÀN BỘ NHẬT KÝ",
	"report.no_attention": "Không có mục chưa đọc.",
	"report.no_today": "Chưa nhận được báo cáo hôm nay.",
	"report.no_history": "Chưa có lịch sử báo cáo.",
	"report.source": "Nguồn: {source}",
	"report.confidence": "Độ tin cậy: {confidence}",
	"report.updated": "Cập nhật: Ngày {day}",
	"report.stale": "Thông tin cũ",
	"report.confirmed": "Đã xác nhận",
	"report.reported": "Theo báo cáo",
	"report.uncertain": "Chưa chắc chắn",
	"report.fresh": "Mới",
	"report.aging": "Đang cũ dần",
	"report.no_data": "Không có dữ kiện.",
	"report.no_internal": "Chưa có báo cáo nội bộ.",
	"report.unit_no_internal": "Tình trạng nội bộ: chưa có báo cáo.",
	"report.initial_observation": "Quan sát ban đầu",
	"report.king_inspection": "Vua kiểm tra trực tiếp",
	"condition.healing": "đang điều trị",
	"condition.away": "đang đi xa",
	"condition.building": "đang tham gia xây dựng",
	"condition.stable": "ổn định",
	"job.manager": "quản lý",
	"job.worker": "lao động",
	"job.builder": "thợ xây",
	"job.idle": "nhàn rỗi",
	"attention.normal": "Bình thường",
	"attention.notice": "Lưu ý",
	"attention.important": "Quan trọng",
	"attention.critical": "Khẩn cấp",
	"relationship.neutral": "Bình thường",
	"relationship.familiar": "Quen thuộc",
	"relationship.close": "Thân thiết",
	"relationship.romance_candidate": "Có thể gắn bó",
	"relationship.bonded": "Đã gắn bó",
	"relationship.section": "QUAN HỆ",
	"relationship.none": "QUAN HỆ · chưa có quan hệ đáng chú ý",
	"relationship.line": "{name} · Thiện cảm {affinity} · Tin cậy {trust} · {status}",
	"relationship.confirm": "GẮN BÓ với {name}",
	"relationship.bonded_report": "{first} và {second} đã lựa chọn gắn bó.",
	"loyalty.section": "TRUNG THÀNH · {value} · {level}",
	"loyalty.stable": "Ổn định",
	"loyalty.dissatisfied": "Bất mãn",
	"loyalty.low_output": "Giảm hiệu suất",
	"loyalty.objects_but_obeys": "Phản đối nhưng phục tùng",
	"loyalty.resists": "Kháng lệnh",
	"loyalty.revolt": "Nổi loạn",
	"loyalty.low_output_hint": "Hiệu suất công việc hiện giảm.",
	"loyalty.objects_hint": "Phản đối nhưng vẫn thi hành; hiệu suất giảm.",
	"loyalty.resists_hint": "Đang kháng lệnh: không nhận mệnh lệnh mới.",
	"loyalty.revolt_hint": "NỔI LOẠN: mất quyền điều khiển và ngừng làm việc.",
	"loyalty.interrogate": "THẨM VẤN",
	"loyalty.interrogation_report": "{name} được Vua thẩm vấn: Trung thành {loyalty}, mức {level} (đã xác nhận).",
	"promotion.section": "TIẾN TRIỂN · {rank} · {merit} Chiến công",
	"promotion.king_exempt": "Vua không tham gia thăng cấp.",
	"promotion.training": "ĐANG HUẤN LUYỆN → {rank} · còn {days} ngày",
	"promotion.planned": "DỰ KIẾN HUẤN LUYỆN → {rank} vào cuối ngày",
	"promotion.none": "Chưa có hướng thăng cấp sẵn sàng.",
	"promotion.ready": "SẴN SÀNG: {targets}",
	"promotion.barracks_section": "HUẤN LUYỆN & THĂNG CẤP",
	"promotion.barracks_inactive": "Doanh trại phải hoạt động trước khi huấn luyện.",
	"promotion.unit_line": "{name} · {rank} · {merit} Chiến công",
	"promotion.path_line": "→ {rank} · cần {merit} · {days} ngày · {status}",
	"promotion.no_candidates": "Chưa có quân phù hợp để thăng cấp.",
	"promotion.train_action": "HUẤN LUYỆN {name} → {rank}",
	"promotion.cancel_action": "Hủy huấn luyện {name}",
	"promotion.ready_short": "SẴN SÀNG",
	"unit.detail": "Loại quân: {rank} · Phe: {faction}\nVị trí nhìn thấy: {cell}{planned}\n{progression}\n{social}\n{condition}\n\nQUÁ KHỨ & KÝ ỨC\n{story}",
	"unit.no_data": "Chưa có dữ kiện.",
	"unit.planned_move": "\nĐã định nước đi → {cell}",
	"unit.planned_inspection": "\nDự kiến: kiểm tra trực tiếp công trình vào cuối ngày",
	"unit.seed.king": "Vua",
	"unit.seed.rook": "Xe",
	"unit.seed.knight": "Mã",
	"unit.seed.pawn_d": "Tốt D",
	"unit.seed.pawn_e": "Tốt E",
	"unit.seed.backstory": "Sống sót sau những ngày thành trì mất màu.",
	"event.waiting_choice": "{title} đang chờ quyết định của Vua.",
	"event.closed": "{title} đã khép lại.",
	"event.refugee_waiting.title": "Những quân cờ ngoài cổng",
	"event.refugee_waiting.description": "Một nhóm nạn dân vẫn chờ bên ngoài thành.",
	"event.refugee_waiting.support": "Tiếp tục hỗ trợ",
	"event.refugee_waiting.wait": "Để họ tiếp tục chờ",
	"event.refugee_waiting.stage1": "Các quân Tốt ngoài cổng đã dựng chỗ trú tạm.",
	"event.refugee_waiting.stage2": "Lương thực và sự chờ đợi đang đè lên khu nạn dân.",
	"event.refugee_waiting.stage3": "Nhóm nạn dân cần một quyết định lâu dài.",
	"event.refugee_waiting.resolution": "Khu nạn dân đã bước sang một trạng thái mới.",
	"event.refugee_aftercare.title": "Tin từ khu nạn dân",
	"event.refugee_aftercare.description": "Quyết định trước đó đang để lại hệ quả.",
	"event.refugee_aftercare.stage1": "Khu nạn dân đã phản hồi quyết định của thành.",
	"event.refugee_aftercare.resolution": "Tin tiếp nối từ khu nạn dân đã được ghi nhận.",
	"event.forest_signs.title": "Dấu hiệu trong rừng",
	"event.forest_signs.description": "Người gác cổng báo có dấu vết lạ phía rừng.",
	"event.forest_signs.observe": "Tiếp tục quan sát",
	"event.forest_signs.ignore": "Không điều tra",
	"event.forest_signs.stage1": "Những dấu vết chưa đủ để kết luận.",
	"event.forest_signs.stage2": "Báo cáo từ rừng đã được gửi về thành.",
	"event.forest_signs.resolution": "Tin từ rừng đã được ghi vào sổ theo dõi.",
	"event.wasteland_work.title": "Khai phá Đất hoang",
	"event.wasteland_work.description": "Công việc ngoài rìa thành đang tiếp diễn.",
	"event.wasteland_work.stage1": "Những ô đất đầu tiên đã được dọn sạch.",
	"event.wasteland_work.stage2": "Đường vào khu khai phá đã thành hình.",
	"event.wasteland_work.resolution": "Đợt công việc tại Đất hoang đã được ghi nhận.",
	"event.wasteland_incident.title": "Trở ngại ở Đất hoang",
	"event.wasteland_incident.description": "Đội khai phá gặp một đoạn nền đất không ổn định.",
	"event.wasteland_incident.reinforce": "Gia cố lối đi",
	"event.wasteland_incident.reroute": "Đi đường vòng",
	"event.wasteland_incident.stage1": "Đội khai phá đang đánh giá đoạn đất yếu.",
	"event.wasteland_incident.stage2": "Lối làm việc mới đã được ổn định.",
	"event.wasteland_incident.resolution": "Trở ngại tại Đất hoang đã được xử lý.",
	"outside.title": "NGOÀI THÀNH",
	"outside.choose_two": "Chọn đúng 2 quân cho chuyến đi hoặc hộ tống:",
	"outside.explore": "Thám hiểm",
	"outside.expedition": "ĐOÀN THÁM HIỂM",
	"outside.return_wait": "Đang chờ chỗ trở về",
	"outside.day_status": "Ngoài thành · Ngày thứ {day}",
	"outside.target": "Hướng tới: {region}",
	"outside.no_news": "Chưa có tin.",
	"outside.unknown_region": "vùng chưa rõ",
	"outside.near_city": "vùng gần thành",
	"outside.cancel_expedition": "Hủy chuyến đi dự kiến",
	"outside.cancel_decision": "Hủy quyết định dự kiến",
	"outside.support": "Hỗ trợ lương thực",
	"outside.stop_support": "Ngừng hỗ trợ",
	"outside.accept_trade": "Chấp thuận trao đổi",
	"outside.reject_trade": "Từ chối trao đổi",
	"outside.resettle": "Tái định cư",
	"outside.people": "{count} người",
	"outside.status": "Trạng thái: {status}",
	"outside.location": "Đang ở: {region}",
	"outside.supported": "Đang được hỗ trợ · {food} Lương thực/ngày",
	"outside.unsupported": "Chưa được hỗ trợ",
	"outside.trade_offer": "Đề nghị: 1 Vật tư ↔ 1 Lương thực",
	"outside.select_region": "Chọn vùng đã biết để thám hiểm",
	"outside.supply_prefix": "Lương thực chuẩn bị: ",
	"outside.planned_expedition": "DỰ KIẾN THÁM HIỂM\n{units}\nĐích: {target} · Chuẩn bị: {food} Lương thực",
	"outside.expedition_detail": "{status}\nHướng tới: {target}\n{news}",
	"outside.group_detail": "{pieces}\n{people}\n{status}",
	"outside.resettling": "Đang tái định cư · còn {days} ngày",
	"outside.planned": "DỰ KIẾN: {action}",
	"outside.action.support": "hỗ trợ",
	"outside.action.stop_support": "ngừng hỗ trợ",
	"outside.action.accept_trade": "chấp thuận trao đổi",
	"outside.action.reject_trade": "từ chối trao đổi",
	"outside.action.resettle": "tái định cư",
	"outside.not_explored": "chưa khảo sát",
	"perimeter.refugee": "KHU TỊ NẠN",
	"perimeter.forest": "RỪNG NGOẠI VI",
	"perimeter.wasteland": "ĐẤT HOANG",
	"perimeter.city": "NỘI THÀNH",
	"perimeter.no_refugees": "Không có nhóm đang chờ",
	"perimeter.quiet": "Yên tĩnh",
	"perimeter.developing": "Đang khai phá · còn {days} ngày",
	"perimeter.complete": "Hoàn tất · sẵn sàng tái định cư",
	"perimeter.not_started": "Chưa khai phá",
	"perimeter.supported": "được hỗ trợ",
	"perimeter.stable": "ổn định",
	"perimeter.uneasy": "bất an",
	"perimeter.tense": "căng thẳng",
	"perimeter.chaos": "hỗn loạn",
	"perimeter.returning": "đang trở về",
	"world.title": "THẾ GIỚI NGOÀI THÀNH",
	"world.overview": "Mùa {season} · {weather}\nLương thực dài hạn: {food} · Vật tư: {materials}",
	"world.regions": "KHU VỰC",
	"world.routes": "TUYẾN ĐƯỜNG",
	"world.factions": "DẤU VẾT PHE KHÁC",
	"world.news": "TIN GẦN ĐÂY",
	"world.observed": "Đã quan sát · Chưa khảo sát trực tiếp",
	"world.region_line": "{presence} · {condition} · Nguy cơ: {danger}",
	"world.route_to": "Tới {destination} · {safety}",
	"world.danger.high": "Cao",
	"world.danger.notice": "Đáng lưu ý",
	"world.danger.low": "Thấp",
	"world.relation.friendly": "Có thiện chí",
	"world.relation.hostile": "Thù địch",
	"world.relation.unknown": "Chưa rõ thái độ",
	"season.spring": "Xuân",
	"season.summer": "Hạ",
	"season.autumn": "Thu",
	"season.winter": "Đông",
	"weather.clear": "Quang",
	"weather.rain": "Mưa",
	"weather.storm": "Bão",
	"weather.cold": "Rét",
	"weather.heat": "Nóng",
	"pressure.surplus": "Dư dả",
	"pressure.stable": "Ổn định",
	"pressure.strained": "Căng",
	"pressure.critical": "Nguy cấp",
	"presence.unknown": "Chưa biết",
	"presence.observed": "Đã quan sát",
	"presence.visited": "Đã ghé",
	"presence.supplied": "Được tiếp tế",
	"presence.connected": "Đã kết nối",
	"presence.influenced": "Có ảnh hưởng",
	"route.blocked": "Bị chặn",
	"route.safe": "An toàn",
	"route.caution": "Cần thận trọng",
	"route.dangerous": "Nguy hiểm",
	"perimeter.resettling": "tái định cư · còn {days} ngày",
	"perimeter.exploring": "thám hiểm · còn {days} ngày",
	"ration.title": "PHÂN KHẨU PHẦN",
	"ration.confirm": "Xác nhận khẩu phần",
	"ration.hunger": "Đói {days}/3",
	"ration.hint": "Còn {remaining} khẩu phần · Đã chọn {selected}/{required}\nQuân nhịn đủ 3 ngày chỉ chết sau khi kết thúc ngày đói thứ ba.",
	"ration.prisoner": "Tù binh {name}",
	"onboarding.board.title": "Đây là nội thành",
	"onboarding.board.body": "Bàn cờ là thành của bạn. Mỗi quân cờ là một người thật đang sống và làm việc tại đây.",
	"onboarding.king.title": "Vua quản lý thành",
	"onboarding.king.body": "Chọn Vua để quản lý và kiểm tra công trình. Vua không tham gia thăng cấp.",
	"onboarding.resources.title": "Kho dự trữ",
	"onboarding.resources.body": "Lương thực nuôi người trong thành; Vật tư dùng để xây dựng và duy trì kế hoạch.",
	"onboarding.unit.title": "Chọn một quân",
	"onboarding.unit.body": "Chọn quân để xem tình trạng, công việc, chiến công, lòng trung thành và các mối quan hệ.",
	"onboarding.report.title": "Đọc báo cáo",
	"onboarding.report.body": "Báo cáo cho biết điều thành thực sự biết. Mục quan trọng sẽ nằm trong Cần chú ý.",
	"onboarding.outside.title": "Ngoài thành",
	"onboarding.outside.body": "Rừng, đất hoang và khu tị nạn nằm quanh thành. Quân rời thành vẫn hiện bằng đúng quân cờ của họ.",
	"onboarding.end_day.title": "Chốt ngày",
	"onboarding.end_day.body": "Kết thúc ngày sẽ chốt mọi quyết định và giải quyết cả ngày. Hãy kiểm tra lệnh dự kiến trước khi bấm.",
	"onboarding.next": "Tiếp",
	"onboarding.dismiss": "Đã hiểu",
	"onboarding.skip": "Bỏ qua hướng dẫn",
	"ending.title": "HỒI KẾT · NGÀY 32",
	"ending.outcome.renewal.title": "Một thành phố hồi sinh",
	"ending.outcome.renewal.body": "Sau ba mươi hai ngày, nội thành không chỉ tồn tại mà đã tìm lại được nhịp sống.",
	"ending.outcome.survived.title": "Thành vẫn đứng vững",
	"ending.outcome.survived.body": "Ba mươi hai ngày đã qua. Thành còn nhiều vết nứt, nhưng những người ở lại vẫn giữ được cổng thành.",
	"ending.outcome.fractured.title": "Một nền hòa bình mong manh",
	"ending.outcome.fractured.body": "Thành sống sót, nhưng bất mãn và thiếu thốn đã để lại những đường nứt khó hàn gắn.",
	"ending.section.city": "THÀNH CÒN LẠI",
	"ending.section.people": "NHỮNG NGƯỜI Ở LẠI",
	"ending.section.lost": "NHỮNG NGƯỜI ĐÃ MẤT",
	"ending.section.changes": "NHỮNG THAY ĐỔI LỚN",
	"ending.section.relationships": "NHỮNG MỐI GẮN KẾT",
	"ending.section.outside": "DẤU VẾT NGOÀI THÀNH",
	"ending.city_line": "{survivors} người còn lại · {buildings} công trình hoạt động · Lương thực {food} · Vật tư {materials}.",
	"ending.survivor_line": "{name} · {rank}.",
	"ending.no_losses": "Không có cái tên nào được ghi vào danh sách người đã mất.",
	"ending.no_major_changes": "Không có thay đổi lớn nào được ghi nhận.",
	"ending.cause.starvation": "chết đói",
	"ending.cause.expedition": "mất tích trong chuyến thám hiểm",
	"ending.cause.execution": "bị hành quyết",
	"ending.loss_line": "{name} · {rank} · mất vào Ngày {day} ({cause}).",
	"ending.promotion_line": "{name} đã trở thành {rank}.",
	"ending.loyalty_line": "{name}: {level}.",
	"ending.relationship_line": "{first} và {second}: {status}.",
	"ending.expedition_line": "{count} chuyến thám hiểm đã hoàn tất.",
	"ending.event_line": "{count} biến cố lớn đã được giải quyết.",
	"ending.outside_line": "{groups} nhóm ngoài thành còn được ghi nhận; {resettled} nhóm đã tái định cư.",
	"ending.close": "Khép lại hành trình",
}

const EN := {
	"brand.name": "After Checkmate",
	"menu.subtitle": "AFTER CHECKMATE",
	"menu.play": "Play",
	"menu.about": "About the Game",
	"menu.settings": "Settings",
	"menu.quit": "Quit",
	"menu.about_title": "AFTER CHECKMATE",
	"menu.about_body": "Lead a chess city rebuilding after war. Manage food, materials, the pieces who survived, and the choices waiting beyond the city gate. This is a living world recovering from conflict, where every decision leaves a trace.",
	"settings.title": "SETTINGS",
	"settings.resolution": "Resolution",
	"settings.master": "Master",
	"settings.bgm": "Music",
	"settings.sfx": "SFX",
	"settings.ambience": "Ambience",
	"settings.mute": "Mute all audio",
	"pause.title": "PAUSED",
	"pause.resume": "Resume",
	"pause.main_menu": "Return to Main Menu",
	"common.close": "Close",
	"common.confirm": "Confirm",
	"common.cancel": "Cancel",
	"common.none": "None",
	"common.unknown": "Unknown",
	"common.day": "Day {day}",
	"game.day_counter": "DAY {day} / {max_day}",
	"game.food": "Food",
	"game.materials": "Materials",
	"game.resources": "   Food {food}   ·   Materials {materials}",
	"game.season_weather": "   {season} · {weather}",
	"game.undo": "Close / Deselect",
	"game.undo_hint": "Close the current panel or cancel a temporary action; planned orders stay intact",
	"game.report": "Reports",
	"game.world": "World",
	"game.end_day": "End Day",
	"game.resolved_day": "Day {day} resolved",
	"game.failure": "DEFEAT: {reason}",
	"failure.outsider_overrun": "{group} overwhelmed the city in the chaos.",
	"game.starved": "Lost to starvation: {names}",
	"game.resource_delta": "{resource} {delta}",
	"rank.pawn": "Pawn",
	"rank.knight": "Knight",
	"rank.rook": "Rook",
	"rank.bishop": "Bishop",
	"rank.queen": "Queen",
	"rank.king": "King",
	"faction.player": "Your side",
	"faction.enemy": "Enemy",
	"faction.outsider": "Outsider",
	"building.farm": "Farm",
	"building.workshop": "Materials Workshop",
	"building.prison": "Prison",
	"building.infirmary": "Infirmary",
	"building.barracks": "Barracks",
	"building.phase.blueprint": "Planned",
	"building.phase.building": "Under construction",
	"building.phase.active": "Active",
	"building.phase.demolishing": "Being demolished",
	"building.palette.title": "3×3 BUILDINGS",
	"building.palette.hint": "The core occupies the center; eight work cells surround it",
	"building.palette.builders": "BUILDERS",
	"building.palette.builder_count": "{count} builders selected",
	"building.palette.cancel_plan": "Cancel planned building",
	"building.palette.cancel_current": "Cancel current construction",
	"building.palette.assign_builder": "Assign selected builders",
	"building.palette.demolish": "Demolish active building",
	"building.palette.cancel_demolition": "Cancel demolition",
	"building.palette.staffing": "STAFFING",
	"building.palette.assign_manager": "Assign selected piece as manager",
	"building.palette.assign_worker": "Assign selected piece as worker",
	"building.palette.cancel_staffing": "Cancel planned staffing",
	"building.palette.choose": "Choose a building type",
	"building.palette.builder_role": "builder",
	"report.title": "DAILY REPORT",
	"report.day_title": "DAY {day} REPORT",
	"report.attention": "NEEDS ATTENTION",
	"report.today_summary": "TODAY SUMMARY",
	"report.full_log": "FULL LOG",
	"report.no_attention": "No unread alerts.",
	"report.no_today": "No reports have arrived today.",
	"report.no_history": "No report history yet.",
	"report.source": "Source: {source}",
	"report.confidence": "Confidence: {confidence}",
	"report.updated": "Updated: Day {day}",
	"report.stale": "Outdated",
	"report.confirmed": "Confirmed",
	"report.reported": "Reported",
	"report.uncertain": "Uncertain",
	"report.fresh": "Fresh",
	"report.aging": "Aging",
	"report.no_data": "No information available.",
	"report.no_internal": "No internal report is available.",
	"report.unit_no_internal": "Internal condition: no report available.",
	"report.initial_observation": "Initial observation",
	"report.king_inspection": "Direct inspection by the King",
	"condition.healing": "receiving treatment",
	"condition.away": "away from the city",
	"condition.building": "working on construction",
	"condition.stable": "stable",
	"job.manager": "manager",
	"job.worker": "worker",
	"job.builder": "builder",
	"job.idle": "idle",
	"attention.normal": "Normal",
	"attention.notice": "Notice",
	"attention.important": "Important",
	"attention.critical": "Critical",
	"relationship.neutral": "Neutral",
	"relationship.familiar": "Familiar",
	"relationship.close": "Close",
	"relationship.romance_candidate": "May become bonded",
	"relationship.bonded": "Bonded",
	"relationship.section": "RELATIONSHIPS",
	"relationship.none": "RELATIONSHIPS · none worth noting",
	"relationship.line": "{name} · Affinity {affinity} · Trust {trust} · {status}",
	"relationship.confirm": "BOND with {name}",
	"relationship.bonded_report": "{first} and {second} chose to form a bond.",
	"loyalty.section": "LOYALTY · {value} · {level}",
	"loyalty.stable": "Steady",
	"loyalty.dissatisfied": "Dissatisfied",
	"loyalty.low_output": "Low output",
	"loyalty.objects_but_obeys": "Objects, but obeys",
	"loyalty.resists": "Resists",
	"loyalty.revolt": "Revolt",
	"loyalty.low_output_hint": "Work output is reduced.",
	"loyalty.objects_hint": "They object, but still comply at reduced output.",
	"loyalty.resists_hint": "Resisting: refuses new orders.",
	"loyalty.revolt_hint": "IN REVOLT: no longer controllable and has stopped working.",
	"loyalty.interrogate": "INTERROGATE",
	"loyalty.interrogation_report": "The King interrogated {name}: Loyalty {loyalty}, status {level} (confirmed).",
	"promotion.section": "PROGRESSION · {rank} · {merit} Merit",
	"promotion.king_exempt": "The King cannot be promoted.",
	"promotion.training": "IN TRAINING → {rank} · {days} days left",
	"promotion.planned": "TRAINING PLANNED → {rank} at day’s end",
	"promotion.none": "No promotion path is currently available.",
	"promotion.ready": "READY: {targets}",
	"promotion.barracks_section": "TRAINING & PROMOTION",
	"promotion.barracks_inactive": "The Barracks must be active before training can begin.",
	"promotion.unit_line": "{name} · {rank} · {merit} Merit",
	"promotion.path_line": "→ {rank} · needs {merit} · {days} days · {status}",
	"promotion.no_candidates": "No eligible piece has a promotion path.",
	"promotion.train_action": "TRAIN {name} → {rank}",
	"promotion.cancel_action": "Cancel {name}'s training",
	"promotion.ready_short": "READY",
	"unit.detail": "Piece: {rank} · Side: {faction}\nVisible position: {cell}{planned}\n{progression}\n{social}\n{condition}\n\nPAST & MEMORIES\n{story}",
	"unit.no_data": "No information available.",
	"unit.planned_move": "\nPlanned move → {cell}",
	"unit.planned_inspection": "\nPlanned: direct inspection at day’s end",
	"unit.seed.king": "King",
	"unit.seed.rook": "Rook",
	"unit.seed.knight": "Knight",
	"unit.seed.pawn_d": "Pawn D",
	"unit.seed.pawn_e": "Pawn E",
	"unit.seed.backstory": "Survived the days when color drained from the city.",
	"event.waiting_choice": "{title} is waiting for the King's decision.",
	"event.closed": "{title} has run its course.",
	"event.refugee_waiting.title": "Pieces Beyond the Gate",
	"event.refugee_waiting.description": "A group of refugees is still waiting outside the city.",
	"event.refugee_waiting.support": "Continue support",
	"event.refugee_waiting.wait": "Leave them waiting",
	"event.refugee_waiting.stage1": "The Pawns outside the gate have raised a temporary shelter.",
	"event.refugee_waiting.stage2": "Hunger and uncertainty are weighing on the refugee camp.",
	"event.refugee_waiting.stage3": "The refugees need a lasting decision.",
	"event.refugee_waiting.resolution": "The refugee camp has entered a new phase.",
	"event.refugee_aftercare.title": "Word from the Refugee Camp",
	"event.refugee_aftercare.description": "The earlier decision is beginning to bear consequences.",
	"event.refugee_aftercare.stage1": "The refugee camp has responded to the city's decision.",
	"event.refugee_aftercare.resolution": "The follow-up from the refugee camp was recorded.",
	"event.forest_signs.title": "Signs in the Forest",
	"event.forest_signs.description": "The gate watch reports strange tracks near the forest.",
	"event.forest_signs.observe": "Keep watch",
	"event.forest_signs.ignore": "Do not investigate",
	"event.forest_signs.stage1": "The tracks reveal too little to draw a conclusion.",
	"event.forest_signs.stage2": "A report from the forest has reached the city.",
	"event.forest_signs.resolution": "The forest report was entered in the watch log.",
	"event.wasteland_work.title": "Developing the Wasteland",
	"event.wasteland_work.description": "Work continues along the city's outer edge.",
	"event.wasteland_work.stage1": "The first plots of ground have been cleared.",
	"event.wasteland_work.stage2": "A workable path into the development has taken shape.",
	"event.wasteland_work.resolution": "This phase of wasteland development was recorded.",
	"event.wasteland_incident.title": "Trouble in the Wasteland",
	"event.wasteland_incident.description": "The development crew found a stretch of unstable ground.",
	"event.wasteland_incident.reinforce": "Reinforce the path",
	"event.wasteland_incident.reroute": "Take a detour",
	"event.wasteland_incident.stage1": "The crew is assessing the weak ground.",
	"event.wasteland_incident.stage2": "A new working route has been stabilized.",
	"event.wasteland_incident.resolution": "The wasteland obstruction was resolved.",
	"outside.title": "OUTSIDE THE WALLS",
	"outside.choose_two": "Choose exactly 2 pieces for an expedition or escort:",
	"outside.explore": "Explore",
	"outside.expedition": "EXPEDITION",
	"outside.return_wait": "Waiting for space to return",
	"outside.day_status": "Outside · Day {day}",
	"outside.target": "Heading toward: {region}",
	"outside.no_news": "No word yet.",
	"outside.unknown_region": "unknown region",
	"outside.near_city": "the city outskirts",
	"outside.cancel_expedition": "Cancel planned expedition",
	"outside.cancel_decision": "Cancel planned decision",
	"outside.support": "Provide food support",
	"outside.stop_support": "Stop support",
	"outside.accept_trade": "Accept trade",
	"outside.reject_trade": "Decline trade",
	"outside.resettle": "Resettle",
	"outside.people": "{count} people",
	"outside.status": "Status: {status}",
	"outside.location": "Location: {region}",
	"outside.supported": "Supported · {food} Food/day",
	"outside.unsupported": "No support",
	"outside.trade_offer": "Offer: 1 Material ↔ 1 Food",
	"outside.select_region": "Choose a known region to explore",
	"outside.supply_prefix": "Food supplies: ",
	"outside.planned_expedition": "PLANNED EXPEDITION\n{units}\nTarget: {target} · Supplies: {food} Food",
	"outside.expedition_detail": "{status}\nHeading toward: {target}\n{news}",
	"outside.group_detail": "{pieces}\n{people}\n{status}",
	"outside.resettling": "Resettling · {days} days left",
	"outside.planned": "PLANNED: {action}",
	"outside.action.support": "provide support",
	"outside.action.stop_support": "stop support",
	"outside.action.accept_trade": "accept trade",
	"outside.action.reject_trade": "decline trade",
	"outside.action.resettle": "resettle",
	"outside.not_explored": "not yet explored",
	"perimeter.refugee": "REFUGEE CAMP",
	"perimeter.forest": "OUTER FOREST",
	"perimeter.wasteland": "WASTELAND",
	"perimeter.city": "INNER CITY",
	"perimeter.no_refugees": "No group is waiting",
	"perimeter.quiet": "Quiet",
	"perimeter.developing": "Development underway · {days} days left",
	"perimeter.complete": "Complete · ready for settlement",
	"perimeter.not_started": "Not yet developed",
	"perimeter.supported": "supported",
	"perimeter.stable": "stable",
	"perimeter.uneasy": "uneasy",
	"perimeter.tense": "tense",
	"perimeter.chaos": "chaos",
	"perimeter.returning": "returning",
	"world.title": "WORLD BEYOND THE WALLS",
	"world.overview": "{season} · {weather}\nLong-term Food: {food} · Materials: {materials}",
	"world.regions": "REGIONS",
	"world.routes": "ROUTES",
	"world.factions": "OTHER FACTIONS",
	"world.news": "RECENT NEWS",
	"world.observed": "Observed · Not yet explored in person",
	"world.region_line": "{presence} · {condition} · Risk: {danger}",
	"world.route_to": "To {destination} · {safety}",
	"world.danger.high": "High",
	"world.danger.notice": "Notable",
	"world.danger.low": "Low",
	"world.relation.friendly": "Friendly",
	"world.relation.hostile": "Hostile",
	"world.relation.unknown": "Unknown stance",
	"season.spring": "Spring",
	"season.summer": "Summer",
	"season.autumn": "Autumn",
	"season.winter": "Winter",
	"weather.clear": "Clear",
	"weather.rain": "Rain",
	"weather.storm": "Storm",
	"weather.cold": "Cold",
	"weather.heat": "Heat",
	"pressure.surplus": "Surplus",
	"pressure.stable": "Stable",
	"pressure.strained": "Strained",
	"pressure.critical": "Critical",
	"presence.unknown": "Unknown",
	"presence.observed": "Observed",
	"presence.visited": "Visited",
	"presence.supplied": "Supplied",
	"presence.connected": "Connected",
	"presence.influenced": "Influenced",
	"route.blocked": "Blocked",
	"route.safe": "Safe",
	"route.caution": "Use caution",
	"route.dangerous": "Dangerous",
	"perimeter.resettling": "resettling · {days} days left",
	"perimeter.exploring": "exploring · {days} days left",
	"ration.title": "RATIONING",
	"ration.confirm": "Confirm rations",
	"ration.hunger": "Hungry {days}/3",
	"ration.hint": "{remaining} rations left · Selected {selected}/{required}\nA piece dies only after the third fully resolved day without food.",
	"ration.prisoner": "Prisoner {name}",
	"onboarding.board.title": "This board is your city",
	"onboarding.board.body": "The board is the city itself. Every chess piece represents a real person living and working here.",
	"onboarding.king.title": "The King manages the city",
	"onboarding.king.body": "Select the King to manage and inspect buildings. The King cannot be promoted.",
	"onboarding.resources.title": "Your stores",
	"onboarding.resources.body": "Food keeps the city alive. Materials turn plans into buildings and keep projects moving.",
	"onboarding.unit.title": "Select a piece",
	"onboarding.unit.body": "Select a piece to see their condition, work, merit, loyalty, and relationships.",
	"onboarding.report.title": "Read your reports",
	"onboarding.report.body": "Reports show what the city genuinely knows. Urgent items rise to Needs Attention.",
	"onboarding.outside.title": "Beyond the walls",
	"onboarding.outside.body": "The forest, wasteland, and refugee camp surround the city. Pieces away from home remain visible there.",
	"onboarding.end_day.title": "Commit the day",
	"onboarding.end_day.body": "End Day commits every planned decision and resolves the day. Review your orders first.",
	"onboarding.next": "Next",
	"onboarding.dismiss": "Got it",
	"onboarding.skip": "Skip tutorial",
	"ending.title": "EPILOGUE · DAY 32",
	"ending.outcome.renewal.title": "A City Reborn",
	"ending.outcome.renewal.body": "After thirty-two days, the inner city is no longer merely surviving. Life has found a rhythm again.",
	"ending.outcome.survived.title": "The City Still Stands",
	"ending.outcome.survived.body": "Thirty-two days have passed. The city bears its scars, but those who remain still hold the gate.",
	"ending.outcome.fractured.title": "A Fragile Peace",
	"ending.outcome.fractured.body": "The city survived, but hunger and dissent left fractures that will not mend quickly.",
	"ending.section.city": "WHAT REMAINS",
	"ending.section.people": "THOSE WHO REMAIN",
	"ending.section.lost": "THOSE WE LOST",
	"ending.section.changes": "WHAT CHANGED",
	"ending.section.relationships": "BONDS THAT ENDURED",
	"ending.section.outside": "BEYOND THE WALLS",
	"ending.city_line": "{survivors} remain · {buildings} active buildings · Food {food} · Materials {materials}.",
	"ending.survivor_line": "{name} · {rank}.",
	"ending.no_losses": "No names were added to the list of the dead.",
	"ending.no_major_changes": "No major change was recorded.",
	"ending.cause.starvation": "starvation",
	"ending.cause.expedition": "lost on expedition",
	"ending.cause.execution": "execution",
	"ending.loss_line": "{name} · {rank} · lost on Day {day} ({cause}).",
	"ending.promotion_line": "{name} rose to {rank}.",
	"ending.loyalty_line": "{name}: {level}.",
	"ending.relationship_line": "{first} and {second}: {status}.",
	"ending.expedition_line": "{count} expeditions reached their conclusion.",
	"ending.event_line": "{count} major events were resolved.",
	"ending.outside_line": "{groups} outside groups remain known; {resettled} were resettled.",
	"ending.close": "Close the journey",
}

static var _locale := DEFAULT_LOCALE
static var _storage_path := DEFAULT_STORAGE_PATH
static var _listeners: Array[Callable] = []


static func set_language(locale: String, persist := true) -> bool:
	var normalized := locale.to_lower()
	if normalized not in SUPPORTED_LOCALES:
		return false
	var changed := normalized != _locale
	_locale = normalized
	if persist:
		_save_language()
	if changed:
		for listener in _listeners.duplicate():
			if listener.is_valid():
				listener.call(_locale)
			else:
				_listeners.erase(listener)
	return true


static func current_language() -> String:
	return _locale


static func load_saved_language() -> String:
	var config := ConfigFile.new()
	if config.load(_storage_path) == OK:
		var saved := str(config.get_value("accessibility", "language", DEFAULT_LOCALE))
		set_language(saved, false)
	return _locale


static func text(key: String, values: Dictionary = {}) -> String:
	var active: Dictionary = VI if _locale == "vi" else EN
	var fallback: Dictionary = EN if FALLBACK_LOCALE == "en" else VI
	var template := str(active.get(key, fallback.get(key, key)))
	for placeholder in values:
		template = template.replace("{%s}" % placeholder, str(values[placeholder]))
	return template


static func has_key(key: String, locale := "") -> bool:
	var target := _locale if locale.is_empty() else locale
	return (VI if target == "vi" else EN).has(key)


static func keys_for(locale: String) -> Array[String]:
	var keys: Array[String] = []
	keys.assign((VI if locale == "vi" else EN).keys())
	keys.sort()
	return keys


static func placeholders_for(key: String, locale: String) -> Array[String]:
	var catalog: Dictionary = VI if locale == "vi" else EN
	var value := str(catalog.get(key, ""))
	var placeholders: Array[String] = []
	var cursor := 0
	while cursor < value.length():
		var opening := value.find("{", cursor)
		if opening < 0:
			break
		var closing := value.find("}", opening + 1)
		if closing < 0:
			break
		var placeholder := value.substr(opening + 1, closing - opening - 1)
		if not placeholder.is_empty() and placeholder not in placeholders:
			placeholders.append(placeholder)
		cursor = closing + 1
	placeholders.sort()
	return placeholders


static func watch(listener: Callable) -> void:
	if listener.is_valid() and listener not in _listeners:
		_listeners.append(listener)


static func unwatch(listener: Callable) -> void:
	_listeners.erase(listener)


static func configure_storage(path: String) -> void:
	_storage_path = path if not path.is_empty() else DEFAULT_STORAGE_PATH


static func reset_for_tests() -> void:
	_locale = DEFAULT_LOCALE
	_storage_path = DEFAULT_STORAGE_PATH
	_listeners.clear()


static func _save_language() -> void:
	var config := ConfigFile.new()
	config.load(_storage_path)
	config.set_value("accessibility", "language", _locale)
	config.save(_storage_path)
